collections:
  people:
    output: true

theme: minima

#defaults:
#  - scope:
#      path: ""
#      type: "people"
#    values:
#      layout: "person"
#  - scope:
#      path: ""
#      type: "posts"
#    values:
#      layout: "post"
#  - scope:
#      path: ""
#    values:
#      layout: "default"
